# Generated by Django 5.2.5 on 2025-08-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leituras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('ph', models.IntegerField()),
                ('tds', models.IntegerField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
